version: '3.9'

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - mongo-volume:/data/db
  db-postgres:
    image: postgres:15-alpine
    volumes:
      - db-postgres-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  mongo-volume:
  db-postgres-volume:
